# Generated by Django 4.2.4 on 2024-04-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_deliveryinformation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinformation',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
