const TYPE = {
    CART_LIST_SUCCESS: "CART_LIST_SUCCESS",
    CART_LIST_FAIL: "CART_LIST_FAIL",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAIL: "ADD_TO_CART_FAIL",
    UPDATE_CART_ITEM_SUCCESS: "UPDATE_CART_ITEM_SUCCESS",
    UPDATE_CART_ITEM_FAIL: "UPDATE_CART_ITEM_FAIL",
    REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
    REMOVE_FROM_CART_FAIL: "REMOVE_FROM_CART_FAIL",
}

export default TYPE
