const TYPE = {

    CART_LIST_SUCCESS: "CART_LIST_SUCCESS",
    CART_LIST_FAIL: "CART_LIST_FAIL",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAIL: "ADD_TO_CART_FAIL",
    UPDATE_CART_ITEM_SUCCESS: "UPDATE_CART_ITEM_SUCCESS",
    UPDATE_CART_ITEM_FAIL: "UPDATE_CART_ITEM_FAIL",
    REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
    REMOVE_FROM_CART_FAIL: "REMOVE_FROM_CART_FAIL",

    ADDRESSES_SUCCESS: "ADDRESSES_SUCCESS",
    ADDRESSES_FAIL: "ADDRESSES_FAIL",
    ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
    ADD_ADDRESS_FAIL: "ADD_ADDRESS_FAIL",
    SELECT_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
    SELECT_ADDRESS_FAIL: "ADD_ADDRESS_FAIL",
    REMOVE_ADDRESS_SUCCESS: "REMOVE_ADDRESS_SUCCESS",
    REMOVE_ADDRESS_FAIL: "REMOVE_ADDRESS_FAIL",
    
}

export default TYPE
