const TYPE = {
    CART_LIST_SUCCESS: "CART_LIST_SUCCESS",
    CART_LIST_FAIL: "CART_LIST_FAIL",
    // CATEGORY_LIST_SUCCESS: "CATEGORY_LIST_SUCCESS",
    // CATEGORY_LIST_FAIL: "CATEGORY_LIST_FAIL",
}

export default TYPE