const TYPE = {
    PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
    PRODUCT_LIST_FAIL: "PRODUCT_LIST_FAIL",
    CATEGORY_LIST_SUCCESS: "CATEGORY_LIST_SUCCESS",
    CATEGORY_LIST_FAIL: "CATEGORY_LIST_FAIL",
    PRODUCT_DETAIL_SUCCESS: "PRODUCT_DETAIL_SUCCESS",
    PRODUCT_DETAIL_FAIL: "PRODUCT_DETAIL_FAIL",
}

export default TYPE