const TYPE = {
    PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
    PRODUCT_LIST_FAIL: "PRODUCT_LIST_FAIL",
    CATEGORY_LIST_SUCCESS: "CATEGORY_LIST_SUCCESS",
    CATEGORY_LIST_FAIL: "CATEGORY_LIST_FAIL",
}

export default TYPE